global:
  domain: c-036d5aa.kyma.ondemand.com
  imagePullSecret:
    name: "container-registry"
#  shootName: df0cf58
#  gateway: kyma-system/kyma-gateway
srv:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: gregorwolf/cap-python-srv-cap
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
srv-python:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: gregorwolf/cap-python-srv-python
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
hana-deployer:
  image:
    repository: gregorwolf/cap-python-hana-deployer
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
backendDestinations:
  srv-api-cap:
    service: srv
  srv-api-python:
    service: srv-python
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: dedicated
    xsappname: cap-python-{{ .Release.Namespace }}
destination:
  serviceOfferingName: "destination"
  servicePlanName: "lite"
  parameters:
    version: "1.0.0"
    HTML5Runtime_enabled: true
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: cap.python
  image:
    repository: gregorwolf/cap-python-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
