###
GET http://localhost:4004/
###
GET http://localhost:4004/health
###
GET http://localhost:4004/odata/v4/catalog
Authorization: Basic alice:
###
GET http://localhost:4004/odata/v4/catalog/Books
Authorization: Basic alice:
